global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.qq.com:25'
  smtp_from: 'zza@jadegread.com'
  smtp_auth_username: 'zza@jadegread.com'
  smtp_auth_password: 'Test@123..'
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'dingtalk'
receivers:
- name: 'mail'
  email_configs:
  - to: 'zza@jadegread.com'
- name: 'dingtalk'
  webhook_configs:
  - url: 'http://dingtalk:8060/dingtalk/dingtalk/send'
    send_resolved: true 
#inhibit_rules:
#  - source_match:
#      severity: 'critical'
#    target_match:
#      severity: 'warning'
#    equal: ['alertname', 'dev', 'instance']
